### ISSUE TITLE
更新数据时间不稳定，有时几十分钟更新一次，有时十几小时没更新

### ISSUE THREAD

**Issue by chenquanhao** [ryanh7/ha-nmc-weather#2]
Logger: custom_components.nmc_weahter
Source: helpers/update_coordinator.py:222
Integration: nmc_weahter
First occurred: 2022年5月3日 17:50:28 (1 occurrences)
Last logged: 2022年5月3日 17:50:28

Error fetching nmc_weather data: Update failed: HTTPConnectionPool(host='www.nmc.cn', port=80): Max retries exceeded with url: /rest/weather?stationid=59659 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9514aac0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by ryanh7** [comment]
看起来像是你的dns问题。无法更新期间检查一下hass所在环境对www.nmc.cn的ip解析结果及网络连通状况。
