### ISSUE TITLE
此项在版本 2024.3.0 中无法工作。请在升级之前解决。

### ISSUE THREAD

**Issue by TIMhao** [ryanh7/ha-nmc-weather#8]
Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
前端版本： 20230906.1 - latest

上述版本中无法使用nmc_weather
提示：The nmc_weather integration is using deprecated forecast
此项在版本 2024.3.0 中无法工作。请在升级之前解决。
The integration nmc_weather is using the deprecated forecast attribute.
Please report it to the custom integration author..

**Comment by ryanh7** [comment]
更新至1.2.0
