### ISSUE TITLE
昨天更新的版本一直提示初始化。

### ISSUE THREAD

**Issue by iJayscn** [ryanh7/ha-nmc-weather#9]
v 1.2.0

昨天更新的版本一直提示初始化。

删除后显示

正在启动“NMC Weather”的配置向导，请稍候

之前一直正常

Home Assistant 2023.9.2
前端版本： 20230911.0 - latest

**Comment by ryanh7** [comment]
提供一下启动配置向导失败后的系统日志

**Comment by iJayscn** [comment]
我自己排查了下 。。。

说出来都好笑

我这里 nmc.cn 被屏蔽了，直连打不开  。。。
